@extends('layouts.master')
@section('content')
@include('partials.DefaultBanner')
@include('partials.Banner')
@include('partials.FindTour')
@include('partials.overview')
@include('partials.packages')
@include('partials.RequestTour')
@endsection
